services:
  mongodb:
    image: mongo:latest
    networks:
      - backend

  java-mongo:
    hostname: java-mongo
    restart: always
    volumes:
      - ./packages/java-mongo/:/app
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      # DATABASE_URL: mongodb://root:prisma@mongodb:27017/test?authSource=admin&retryWrites=true&w=majority&directConnection=true
    build:
      context: "./packages/java-mongo"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.123.0/24
