---
- hosts: vultr
  # user: ubuntu
  # gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Delete content & directory
      file:
        state: absent
        path: ~/java-learn/

    - name: Clone Repository
      git:
        repo: https://github.com/plh97/java-learn.git
        dest: ~/java-learn
        clone: yes
        update: yes
        version: main

    - name: deploy
      command:
        chdir: ~/java-learn
        cmd: docker compose -f ./docker-compose.dev.yml up -d
