---
- hosts: aws
  # user: ubuntu
  # gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:

    # - name: install docker
    #   command:
    #     chdir: ~/SOS
    #     cmd: snap install docker

    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Delete content & directory
      file:
        state: absent
        path: ~/SOS/

    - name: Clone Repository
      git:
        repo: https://github.com/plh97/SOS.git
        dest: ~/SOS
        clone: yes
        update: yes
        version: main

    # - name: deploy
    #   command:
    #     chdir: ~/SOS
    #     cmd: docker compose -f ./docker-compose.dev.yml up
...
